/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ProjetoTransformer from '#transformers/projeto_transformer'
import type TecnologiaTransformer from '#transformers/tecnologia_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Projeto = InferData<ProjetoTransformer>
  export namespace Projeto {
    export type Variants = InferVariants<ProjetoTransformer>
  }
  export type Tecnologia = InferData<TecnologiaTransformer>
  export namespace Tecnologia {
    export type Variants = InferVariants<TecnologiaTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
